### ISSUE TITLE
Allow for multiple connection strings

### ISSUE THREAD

**Issue by cgoldammer** [Soostone/snaplet-persistent#15]
Hi, thanks for this fantastic package.

I'm building a snap application, and I'd like to use multiple databases (`prod` and `test`) so I can populate the `test` database with fake data. If I understand it right, this is currently not possible, because the config provides a unique configuration string.

My current plan is to change the config so that it takes a list of connection strings (one of them is the default) and that I can pass a command line argument (something like `--snap-db = test`) to choose the non-default database.

Does that sound reasonable? I'm not an expert in this package, so very possible a better solution exists. I'm planning to put in a merge request if I have a clean version, but only if you feel that the approach makes sense.

**Comment by MichaelXavier** [comment]
Disclaimer: I'm not much of a snap best practices expert. Are you trying to use multiple databases *at the same time* or are you trying to have different database configs for different environments and be able to boot your app with some particular environment like prod/test? If the latter, I don't think this would require a change to this library. I think the convention would be to have a separate full app config for each environment, e.g. `devel.cfg`, `test.cfg`, etc. You use [commandLineAppConfig](https://hackage.haskell.org/package/snap-1.0.0.1/candidate/docs/Snap-Snaplet-Config.html) to load the config in your `main`. That gives you an argument `-e ENVIRONMENT` which will determine which config is loaded.

**Comment by cgoldammer** [comment]
@MichaelXavier Thanks - I think this is exactly what I'm looking for. Wasn't even aware that this was a feature baked into Snaplets. Let me close this issue.
