### ISSUE TITLE
Why `runPersist` expects a `SqlPersistT (ResourceT (NoLoggingT IO)) b` action instead of a `SqlPersistM b`?

### ISSUE THREAD

**Issue by CristhianMotoche** [Soostone/snaplet-persistent#19]
The [`runPersist`](https://hackage.haskell.org/package/snaplet-persistent-0.5.1/docs/Snap-Snaplet-Persistent.html#v:runPersist) functions has the following type: 

```haskell
:: HasPersistPool m 
=> SqlPersistT (ResourceT (NoLoggingT IO)) b 
-> m b
````
What about having the same stack as [`SqlPersistM`](http://hackage.haskell.org/package/persistent-2.8.2/docs/Database-Persist-Sql.html#t:SqlPersistM)?

```haskell
type SqlPersistM = SqlPersistT (NoLoggingT (ResourceT IO)) 
```

Currently, I defined my persistent actions as `foo :: SqlPersistM [Entity Foo]` and I had to create my own `runPersist` and `withPool` with a different:

```haskell
withPool :: MonadIO m
         => ConnectionPool
         -> SqlPersistM a
         -> m a
```

Would this be a good approach?

**Comment by MichaelXavier** [comment]
This is fixed in `snaplet-persistent-0.6.0`
