### ISSUE TITLE
generalize for other backends?

### ISSUE THREAD

**Issue by osa1** [Soostone/snaplet-persistent#2]
I think this library could easily be generalized to support multiple backends. Currently I'm using it for SQLite and I only had to implement one function:

```
initPersist :: SqlPersistT (NoLoggingT IO) a -> SnapletInit b PersistState
initPersist migration = makeSnaplet "persist" description Nothing $ do
    p <- mkSqlitePool
    liftIO . runNoLoggingT $ runSqlPool migration p
    return $ PersistState p
  where
    description = "Snaplet for persistent DB library"
    mkSqlitePool = createSqlitePool "db" 1
```

so if we could provide a way for users to initialize `PersistState`, I guess all `Persistent` functionality would be available to users in snap, for all backends.

I'm willing to make required changes for this if you find the idea reasonable.

**Comment by mightybyte** [comment]
This was fixed in 0.4.1
